
---
---

## Publications
1. **Sun, B.**, Kolesnikov, S., Goldstein, A., & Chan, G. (2021). A dynamic approach for identifying technological breakthroughs with an application in solar photovoltaics. Technological Forecasting and Social Change, 165, [120534](https://www.sciencedirect.com/science/article/abs/pii/S0040162520313603?via%3Dihub).

1. Konidena, R., **Sun, B.**, & Bhandari, V. (2020). Missing discourse on microgrids-The importance of transmission and distribution infrastructure. The Electricity Journal, 33(4), [106727](https://www.sciencedirect.com/science/article/pii/S1040619020300191).

1. Glewwe, P., Shen, R., **Sun, B.**, Wisniewski, S. (2020) Chapter 27 - Teachers in developing countries. The Economics of Education (Second Edition) A Comprehensive Overview. Pages 371-389. [ISBN: 9780128153918](https://www.sciencedirect.com/science/article/pii/B9780128153918000276).

1. **Sun, B.**; Eryilmaz, D.; Konidena, R. "Transparency in Long-Term Electric Demand Forecast: A Perspective on Regional Load Forecasting". IEEE Smart Grid Newsletter, [August 2019](https://smartgrid.ieee.org/newsletters/august-2019/transparency-in-long-term-electric-demand-forecast-a-perspective-on-regional-load-forecasting).

1. **Sun, B.**; Apland, J. "Optimal bus scheduling considering operating costs and emissions: a multiple objective, mixed integer programming framework". Public Transport, 11(2), [237-267](https://link.springer.com/article/10.1007/s12469-019-00199-9).

1. **Sun, B.** (2018). Heterogeneous direct rebound effect: Theory and evidence from the Energy Star program. Energy Economics, 69, [335-349](https://www.sciencedirect.com/science/article/pii/S0140988317304176).

1. Damon, A., Glewwe, P. , Wisniewski, S. and **Sun, B.** (2019), What education policies and programmes affect learning and time in school in developing countries? A review of evaluations from 1990 to 2014. Review of Education, 7(2), [295-387](https://onlinelibrary.wiley.com/doi/full/10.1002/rev3.3123).

1. Damon, A., Glewwe, P., Wisniewski, S., & **Sun, B.** (2016). Education in Developing Countries-what Policies and Programmes Affect Learning and Time in School?. Expertgruppen for bistandsanalys (EBA). [ISBN:978-91-88143-12-9](https://www.oecd.org/derec/sweden/Rapport-Education-developing-countries.pdf).

---

## Working papers
1. Glewwe, Paul; Wisniewski, Suzanne; **Sun, Bixuan**. "Teachers in Developing Countries". (In press)

1. Eryilmaz, Derya; **Sun, Bixuan**. "Impacts of electric vehicle adoption on utility short and long term planning"

1. **Sun, Bixuan**. "Heterogeneous Impacts of Residential Solar Rebate Programs in the U.S.: A Machine Learning Perspective". 

1. **Sun, Bixuan**; [Miller, Steve](stevejmiller.com). "Market power and the transition to clean energy".

1. [Miller, Steve](stevejmiller.com); **Sun, Bixuan**. "Measuring knowledge diversity and its effects".

1. [Miller, Steve](stevejmiller.com); **Sun, Bixuan**. "Research portfolio diversity and breakthrough technologies in the renewable energy sector".

---
## Programming
Apland, Jeffrey; **Sun, Bixuan**. A Multi-Period, Multiple Objective, Mixed Integer Programming, GAMS Model for Transit System Planning. AgEcon Search, Staff Paper [P19-3](https://ageconsearch.umn.edu/record/285068).



